apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: "{{ .Release.Name }}"
  namespace: "{{ .Release.Namespace }}"
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
  annotations:
    marketplace.cloud.google.com/deploy-info: '{"partner_id": "partner", "product_id": "kong", "partner_name": "Partner"}'
spec:
  descriptor:
    type: kong
    version: '5.0.2'
    description: |-
      Kong Konnect is the only API management platform designed from the ground up for the
      cloud native era, delivered as a service. The global control plane is hosted in the cloud by
      Kong, while the runtimes, Kong Gateway - the fastest and most adopted API gateway - run
      within your preferred environment...
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ .Release.Name }}"
  addOwnerRef: true
  componentKinds:
  - group: 'v1'
    kind: Secret
  - group: 'v1'
    kind: Service
  - group: apps/v1
    kind: Deployment
