apiVersion: v1
data:
  tls.key: {{ .Values.TLS_CERTIFICATE_KEY }}
  tls.crt: {{ .Values.TLS_CERTIFICATE_CRT }}
kind: Secret
metadata:
  name: kong-cluster-cert
  namespace: "{{ .Release.Namespace }}"
type: kubernetes.io/tls
