apiVersion: v1
data:
  tls.key: {{ .Values.tls_key }}
  tls.crt: {{ .Values.tls_crt }}
kind: Secret
metadata:
  annotations:
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
  name: kong-cluster-cert
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
