x-google-marketplace:
  schemaVersion: v2

  applicationApiVersion: v1beta1

  publishedVersion: '3.0.0'
  publishedVersionMetadata:
    releaseNote: >-
      A regular update.
    releaseTypes:
      - Feature
    recommended: false
  images:
    '':
      properties:
        image.repository:
          type: REPO_WITH_REGISTRY
        image.tag:
          type: TAG

properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  cluster_server_name:
    type: string
    default: "default"
  cluster_telemetry_server_name:
    type: string
    default: "default"
  tls_crt:
    type: string
    default: "YQo="
  tls_key:
    type: string
    default: "YQo="

required:
- name
- namespace
- cluster_server_name
- cluster_telemetry_server_name
- tls_crt
- tls_key
