x-google-marketplace:
  schemaVersion: v2

  applicationApiVersion: v1beta1

  publishedVersion: '3.0.0'
  publishedVersionMetadata:
    releaseNote: >-
      A regular update.
    releaseTypes:
      - Feature
    recommended: false
  images:
    '':
      properties:
        image.repository:
          type: REPO_WITH_REGISTRY
        image.tag:
          type: TAG

properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  cluster_server_name:
    type: string
    default: "default"
  cluster_telemetry_server_name:
    type: string
    default: "default"
  tls_crt:
    type: string
    # default cert is not valid. Just for the gcp marketplace deployer integration test.
    default: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURsRENDQW42Z0F3SUJBZ0lCQVRBTEJna3Foa2lHOXcwQkFRMHdOREV5TUFrR0ExVUVCaE1DVlZNd0pRWUQKVlFRREhoNEFhd0J2QUc0QWJnQmxBR01BZEFBdEFHUUFaUUJtQUdFQWRRQnNBSFF3SGhjTk1qSXdPVE13TVRjMApNakkzV2hjTk16SXdPVE13TVRjME1qSTNXakEwTVRJd0NRWURWUVFHRXdKVlV6QWxCZ05WQkFNZUhnQnJBRzhBCmJnQnVBR1VBWXdCMEFDMEFaQUJsQUdZQVlRQjFBR3dBZERDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVAKQURDQ0FRb0NnZ0VCQUwwOFhIRWNLbGtObjdFTVBRTlV1SkpqNkxoejZKclNLOElKMW4yYlppRC84a09GM2dNcQpUaVZmRnpvWmVEV0NWT1NIWk93Z3JZVGIzWG5nSEZNRnI0Y0RXNTdOS2dUNWQ5L2ZJc2gvaFJPZ2tZUG9lSGhqCldhSW5ON3hOeHlDQ20rL1hPVVZJSGVkTVJoZmJDMmdRelB5UkViY0N3eE51Q014WkJJMEJVWEVTckpJM1hBbVEKZm1DMW1pYlpnRjcyWnM1T0NZN0crU3NTSmVzb0M5RnEybm1BcWllUUdnbTZyQzhZbVkvSWRtVEFpUlA4dWJRSQpTbkl5V0lCN3R1SytjTTA1Qm4xQmJMNEFzbnA3ZHdmRTNWNGJBK3NYeDFHU0dMK0pRcHZZblZEWDlkNlNNQ1N1CjBHVmwvU014WTBMb3RoeHhoUDJHYWR4RmFLNVBjZ0w5K1VzQ0F3RUFBYU9CdERDQnNUQVNCZ05WSFJNQkFmOEUKQ0RBR0FRSC9BZ0VETUFzR0ExVWREd1FFQXdJQUJqQWRCZ05WSFNVRUZqQVVCZ2dyQmdFRkJRY0RBUVlJS3dZQgpCUVVIQXdJd0Z3WUpLd1lCQkFHQ054UUNCQW9NQ0dObGNuUlVlWEJsTUNNR0NTc0dBUVFCZ2pjVkFnUVdCQlFCCkFRRUJBUUVCQVFFQkFRRUJBUUVCQVFFQkFUQWNCZ2tyQmdFRUFZSTNGUWNFRHpBTkJnVXBBUUVCQVFJQkNnSUIKRkRBVEJna3JCZ0VFQVlJM0ZRRUVCZ0lFQUJRQUNqQUxCZ2txaGtpRzl3MEJBUTBEZ2dFQkFHT2toVHIvdUk4UQoydnhKUEtvUzR1dTRYWGY1Y1FRM0x6L0ZNUktNUDFpaTJQeXZWbXdkTlRGbHRIWU9pNHFyVzd1UWRVL0dLcml6Cnl3SlJaTTJWaDZYdWZlTUYzaWNnWUdQUDZqczhYUCs5WUhNNHcyV01PWFlLcmU3STRvZVNQeTFxdE11bloxZ1AKYkx6ZVJ4d0h2QjBiajczOUdMU0FLNUVqcGxzdVZINitXd0VlQ1c4eEFrVHNMTEVoOE5GUnNTYVowbTd2RWtkcAp6cmdmYjA3aXhwNVUyMVp4TWlPeVJCQVhpQmxDMURiUkxqK2ZlNXJZUmdVSFVyWnl1NzByRkVxajZkRUtCVzF4CmdCdEphOFYrN0ttaFdyTXcxKzg3U0RqWmVBK2kvMHZENklRWkpqYVYyc2g5TUUzQ3RMcWNyYk51L2dLckJVNnUKZFJ1eCs5RUlpQUk9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0="
  tls_key:
    type: string
    # default key is not valid. Just for the gcp marketplace deployer integration test. 
    default: "LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktnd2dnU2tBZ0VBQW9JQkFRQzlQRnh4SENwWkRaK3gKREQwRFZMaVNZK2k0YytpYTBpdkNDZFo5bTJZZy8vSkRoZDRES2s0bFh4YzZHWGcxZ2xUa2gyVHNJSzJFMjkxNQo0QnhUQmErSEExdWV6U29FK1hmZjN5TElmNFVUb0pHRDZIaDRZMW1pSnplOFRjY2dncHZ2MXpsRlNCM25URVlYCjJ3dG9FTXo4a1JHM0FzTVRiZ2pNV1FTTkFWRnhFcXlTTjF3SmtINWd0Wm9tMllCZTltYk9UZ21PeHZrckVpWHIKS0F2UmF0cDVnS29ua0JvSnVxd3ZHSm1QeUhaa3dJa1QvTG0wQ0VweU1saUFlN2Jpdm5ETk9RWjlRV3krQUxKNgplM2NIeE4xZUd3UHJGOGRSa2hpL2lVS2IySjFRMS9YZWtqQWtydEJsWmYwak1XTkM2TFljY1lUOWhtbmNSV2l1ClQzSUMvZmxMQWdNQkFBRUNnZ0VBQ2ZqTDBFUVJNVGNvRXA3WCtqeDFLM1dyVmtqNVdXczQxaFZKb2IzV0lHZ00KWHFXSHdQZnlQVUxwQ08wOXFlZ3Z6QWtjZHRyeitkdlNMSEYwWEtXZ2pjZE9CU3kvaVpxUnlCRE1sdTh0Vm83dwpEQmpzZkQrVUFoajU5V2pOMVBjOCsyTUdpQkdZVGM5MXBCMHRXVE1GY2t1OHVMMmpCUHVYNkJqS3hobHJMcitiCmNrQ2phcE1ZNjZlRENVLzM2d2V5MzIwZ2VkeGp1TXhzSXF5dVBQc2E1dWs0b09uN1VmTEJaNCthTVRDU3BZK3QKNDVZMWRINUM1dVgvQWVGb2RkZkUzZlRDKzhZRnVsYmdUMlBhMFdlN3BsbHRwT2RRN1JTaDVjZlVRRVd0VHRidAphQkxiK0RDVmpXM0EzRTRNK3FGV0JSUlVEVWNBQ1EvamxkeDYvbCt6RlFLQmdRRG0xNjZkZlkvZVAxV1FlOHV2CmpCUVdteHNvZ2toclJsR2FvMkh0MU9QYVlNRTdVZVFrdXNEeGRJZ29MdGllNzBCRjZGUmVHMDRzTmxsQUhKWDUKenNTVjRzbEtsM1BsK0hUdTdzVXBVblRUeGR3VitpL01CMmZYMXFLR1lodm1DTmRIWUtXUHVmSXBSN3creUkvUQpzeEJWcUdpY0Q3WXU0MEFYdmlLRXNtQWc1UUtCZ1FEUjIrS21FYWRXektiMnZkaFF4SzRQZWkwUk81Tk55OVdqClp0alhRYk01NmtLMXpVbC8wa0FEYkxGTXZPaml3T2JiMnBkOW16RzdIUHM4OGI4OXRVTEgveHZKOFRmVFVabysKcHZFYnc1UVZKd3dLa1JsYy8yY21yTTNUZFFIeC9UbzVPTWZScTlFckQrMUFvUThjdVBaMkpGSmNWb1BSanZ5WQpZUFMyUDdOK2J3S0JnUUN4dlc0UWkyWmo3SVlZV29scG9FU3paemdSQjhkMCtjN0piM1Z1cDFYTmhtUWlKWnF4CmdTNGdlK1orY2h1T3ZJN1RoT0M1R1BNbTdhM294Rm5oMzRmVUZLdUNpSHpQbkcrRXJVb1gyQXBtS05tZC9tWWgKQmE2NkxPUTA3b09tcWpZQUduVS81aCtFRTF6cFJvb2RXbEtBY2N3aUphTFVGVnY3TEFYdUFGNHQxUUtCZ0RzNQpRYUk2TXk1a3ZPMi9MOC9EWVpmT2srOWNEN3NSdmkzSjlZSHg4YUZ6Z2ZZS2hDYUZjRGxITUZZR3JmWm9GLzZOCmx0a0V0aWtuQ2FQdVdWa1IwVkhkcGJyOHp4TmM0Um16UlRIZnBPZS9TRCtuS1RBOGg2QzdmYTZpUTdWR0VHdGIKb2RDREc1bDZlaXNXQ016RFNoS1hONE1GaTFmVmNXV1RYeHdicUEwVEFvR0JBTG9wTC9DdFVxaytYYk5ISlNPQQpLb3JudnY2elB6a3lnMUJ1WXlPdXBSUW5EdlNQL1pBc1JENm4zYlo1VThhS2hxYlNhWDV3TThQNmZ3WFZIUmRnCjdRM3pGTjIrRUx3dFl0NHV4MU4yZjBSTU1xWDV5WlY5cVRST0RGbVNkZ0RSSGh1b0tqTGZ4TE5PTXR2QzFXWFoKM2FidnRYamdTd015QjdjQTdKOFhwbG5hCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0="

required:
- name
- namespace
- cluster_server_name
- cluster_telemetry_server_name
- tls_crt
- tls_key
